language: python
python:
  - "2.7"
  - "3.6"
install:
  - "pip install -r requirements-testing.txt"
  - "pip install coveralls"
  - "pip install codacy-coverage"
  - "python setup.py install"
script:
  - nosetests --with-coverage --cover-package=threatingestor
after_success:
  - coveralls
  - coverage xml
  - python-codacy-coverage
