general:
    daemon: true
    sleep: 900
    state_path: state.sqlite3

credentials:
  - name: github-auth
    username: USER
    # Could also use password instead https://github.blog/2013-05-16-personal-api-tokens/
    token: MYTOKEN
                
sources:
  - name: github-query
    module: github
    credentials: github-auth
    saved_state: 
    search: CVE-2018-

operators:
  - name: csv
    # Write artifacts to a CSV file
    module: csv
    filename: output.csv
